name: Vaddiraju Code Development Unit
description: Motive to make fully automated world with APIs
avatar: https://avatars.githubusercontent.com/u/112264612
google_analytics: G-L0BXR0ZGW7
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
exclude: [.gitignore,LICENSE,.github/,_config.yml]
